name: rv-starter-lando

recipe: wordpress

config:
  php: 8.2
  composer_version: 2
  webroot: .
  cache: memcached
  ssl: false
  via: nginx
  xdebug: true
  config:
    php: .local/php.ini
    database: .local/mysql.cnf

proxy:
  appserver_nginx:
    - rv-starter.local

services:
  database:
    portforward: 3307
  mailhog:
    type: mailhog
    portforward: true
  appserver:
    build_as_root:
      # Install required packages
      - apt-get update -y
      - apt-get install -y zlib1g-dev libzip-dev unzip curl

      # Install memcache
      - yes | pecl install memcache-8.0
      - docker-php-ext-enable memcache

      # Install Composer globally
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    memcached:
      type: memcached:1.6.21
      portforward: true

events:
  pre-start:
    - bash .local/bin/pre-start.sh
  post-start:
    - bash .local/bin/post-start.sh

tooling:
  wp:
    service: 'appserver'
  import-db:
    description: Imports .local/db-dumps/mysql.sql into the WordPress database.
    service: appserver
    cmd:
      - if [ ! -e ".local/db-dumps/mysql.sql" ]; then echo "Database file (.local/db-dumps/mysql.sql) does not exist."; exit 1; fi
      - wp db import .local/db-dumps/mysql.sql
      - wp search-replace https://rv-starter.com http://rv-starter.local
      - wp cache flush
      - wp rewrite flush
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm && echo "Enabling xdebug"
    user: root
  xdebug-off:
    service: appserver
    description: CUSTOM Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm && echo "Disabling xdebug"
    user: root
